### ISSUE TITLE
ECMDERR Failed to execute

### ISSUE THREAD

**Issue by karneaud** [Gottwik/enduro_mirror#2]
Trying to install the tools to develop themes and on trying to install bower components I get

> ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/FortAwesome/Font-Awesome.git", exit code of #128 fatal: Not a git repository: ../.git/modules/src

**Comment by Gottwik** [comment]
that's weird because running `git ls-remote --tags --heads https://github.com/FortAwesome/Font-Awesome.git` it's working for me. What version of bower, node and npm are you using? Are you able to run `git clone https://github.com/FortAwesome/Font-Awesome.git`?

**Comment by karneaud** [comment]
@Gottwik I think there may be a problem with the version of node I'm running. I'm running the latest node and i'm trying to substitute yarn for bower. As a result I have to move stuff over from bower to nam packages. Will let you know my finding.



Question can enduro be installed via web pack?

**Comment by Gottwik** [comment]
ok, let me know if I could help with this.

Not sure on the enduro+webpack thing. I guess enduro and webpack do similar thing and not sure how the combination of them would work and what the use cases would be. Enduro uses gulp internally for frontend build-tool purposes, btw.

**Comment by karneaud** [comment]
@gottwik thought as much. I'm trying to "Dockerize" a project using enduro+yarn using the mirror theme. will let you know how it pans out

**Comment by Gottwik** [comment]
excited to hear about how did it go. Maybe you could also document your learnings for people trying to do the same thing.

**Comment by Gottwik** [comment]
I'll go ahead to close this ticket. Feel free to reopen if you have any questions 😄
