### ISSUE TITLE
I have an issue importing sass file. I am seeing the below screenshot when trying to start the server

### ISSUE THREAD

**Issue by harshakakumanu** [Gottwik/enduro_mirror#6]
![screen shot 2017-08-22 at 2 56 27 pm](https://user-images.githubusercontent.com/3950976/29589903-20bb18ae-874c-11e7-9440-3ccac4c18b6c.png)

**Comment by Gottwik** [comment]
That's interesting. Can you check if you have the `_generated/style_stylesheet/index.html` in the project's folder? Do you have `_generated/index.html` there?

This could be mismatch between enduro version, could you check the version(`enduro --version`)?

**Comment by harshakakumanu** [comment]
@Gottwik I fixed the issue by updating Enduro to latest version and Uninstalling/ Installing the nodejs. For the previous version I dont have the `_generated/index.html` but it got fixed itself.

**Comment by Gottwik** [comment]
Awesome, good job 😄 .

Let us know if you stumble across anything else and good luck with the project.
